package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     *查询用户的购物信息
     * */
    List<Cart> findCartsByUserid(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);
    int updateByPrimaryKeyBySelectActive(Cart cart);

    /**
     * 判断购物车是否全选
     * @return  0 ：全选
     * */
    public  int  isAllChecked(Integer userid);

    Cart  findCartByProductIdAndUserid(@Param("productId") Integer productId, @Param("userId") Integer userid);

    /**
     * 批量删除
     * */
    int deleteByUseridAndProductIds(@Param("productIdList") List<String> productIdList,
                                    @Param("userid") Integer userid);

    /**
     * 选中/取消选中
     * */
    int  checkedOrUncheckedProduct(@Param("userid")Integer userid,
                                   @Param("productId") Integer productId,
                                   @Param("checked") Integer checked);
    /**
     * 查询购物车中商品数量
     * */
    int selectCartProductCount(Integer userid);

    /***
     *
     * 查询购物车中用户要购买的商品
     */
    List<Cart> selectCheckedCartByUserid(Integer userId);

}